name: "Test-flinging"
description: "Submits a job YAML to a Testflinger server"
inputs:
  job:
    description: "Job YAML string (see https://canonical-testflinger.readthedocs-hosted.com/en/latest/reference/job-schema/ for more info)"
    required: true
  server:
    description: The Testflinger server to use
    required: false
    default: 'testflinger.canonical.com'
runs:
  using: "composite"
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo snap install yq testflinger-cli

    - name: Test testflinger connection
      shell: bash
      run: |
        nc -vz ${{ inputs.server }} 443

    - name: Build job definition
      shell: bash
      run: |
        echo "${{ inputs.job }}" | yq eval -P - > job.yaml
        # diagnostics
        cat job.yaml

    - name: Submit job to Testflinger and optionally poll
      shell: bash
      run: |
        JOB_ID=$(testflinger --server https://${{ inputs.server }} submit --quiet job.yaml)
        echo "job id: $JOB_ID"
