name: Test-flinging
description: Submit a job YAML to a Testflinger server
inputs:
  job:
    description: "Job YAML string (see https://canonical-testflinger.readthedocs-hosted.com/en/latest/reference/job-schema/ for more info)"
    required: true
  server:
    description: The Testflinger server to use
    required: false
    default: testflinger.canonical.com
runs:
  using: composite
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo snap install testflinger-cli

    - name: Test connection to Testflinger server
      shell: bash
      run: |
        nc -vz ${{ inputs.server }} 443

    - name: "Display job"
      shell: bash
      run: |
        cat ${{ inputs.job }}

    - name: "Submit job"
      shell: bash
      run: |
        JOB_ID=$(testflinger --server https://${{ inputs.server }} submit --quiet ${{ inputs.job }})
        echo "job id: $JOB_ID"
